title: Mohammed Sani
description: PhD Candidate in Architectural Engineering â€“ RFH-MDO: Real-Time Human-Centric Building Optimization
url: https://msaniguero64-lgtm.github.io
baseurl: ""
name: Mohammed Sani
photo: /assets/images/profile.jpg
